### ISSUE TITLE
async_write_some handler's executor

### ISSUE THREAD

**Issue by SimonEbner** [RobertLeahy/CppCon2018Talk#1]
Great talk, I learned a lot. I am implementing some of the best practices in my own code. I have one detail question to your `mock_async_write_stream`. In `mock_async_write_stream::async_write_some` you invoke the handler via
```
std::net::post(std::net::bind_executor(ex_, std::bind(std::forward<Handler>(h), ec, bytes)));
```

Would it not be appropriate to use the handler's executor and only fallback to the socket's excecutor if the handler does not have an associated executor? I imagine sth along the following lines
```
auto associated_executor = std::net::get_associated_executor(handler, ex_);
std::net::post(std::net::bind_executor(associated_executor, std::bind(std::forward<Handler>(h), ec, bytes)));
```

**Comment by RobertLeahy** [comment]
The second code snippet is indeed more correct given the guarantees of Boost.Asio/the Networking TS.

The testability example (including `mock_async_write_stream`) appear earlier in the talk than coverage of associated executors, hence the omission.

**Comment by SimonEbner** [comment]
I get that. Thanks for clarifying
